## defaults for all profiles
[profile.default]
src = 'src'                   # the source directory
test = 'test'                 # the test directory
out = 'out'                   # the output directory (for artifacts)
libs = ['lib']                # a list of library directories
cache = true                  # cache the builds
cache_path = 'cache'          # where the cache is stored
solc_version = '0.8.21'       # override for the solc version
optimizer = true              # enable the solc optimiser
optimizer_runs = 999999       # the number of optimiser runs
verbosity = 4                 # the verbosity of tests
evm_version = 'paris'         # set the EVM target version
