name: Test Windows Foundry Build

on: [workflow_dispatch]

jobs:
    build_and_test:
      name: Foundry
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
        - run: cargo install --git https://github.com/foundry-rs/foundry --profile local --force foundry-cli anvil chisel
